version: '3.8'
services:
  nest-app:
    build: .
    restart: always
    ports:
        - '3000:3000'
    links:
        - postgres 

  postgres:
    image: postgres
    depends_on:
      - nest-app
    ports:
      - '5433:5432'
    restart: always
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Pass_123
